### ISSUE TITLE
[4.1][Package / Custom Field] Field type text_suggestions_from_array aka Autocomplete

### ISSUE THREAD

**Issue by chriscalip** [Laravel-Backpack/addons#15]
Who wants it? Can we have it?

Autocomplete from array, text_suggestions_from_array
![datalist-default](https://user-images.githubusercontent.com/479454/38952683-132ba942-4312-11e8-978b-f42e2778c7a1.gif)
![flexdatalist](https://user-images.githubusercontent.com/479454/38966227-c2da7344-4346-11e8-9e01-72cd7df94f14.png)

Difference between select2 and autocomplete datalist?
Think of it as the difference between a requirement and a suggestion. For the select element, the user is required to select one of the options you've given. For the datalist element, it is suggested that the user select one of the options you've given, but he can actually enter anything he wants in the input. 

~~All features found in https://laravel-backpack.readme.io/docs/crud-fields#section-select_from_array
with an additional feature of "or_other"~~
~~Roughly same feature: https://www.drupal.org/project/select_or_other~~

**Comment by dandarie** [comment]
Hi.

I was able to create a tags field with minimal effort using the [dynamic option creation](https://select2.org/tagging) feature of select2:

```
$this->crud->addField([
            'name' => 'tags',
            'fake' => true,
            'store_in' => 'extras',
            'type' => 'select2_from_array',
            'allows_multiple' => true,
            'attributes' => [
                'data-tags' => true
            ],
            'options' =>[
                // existing options
            ],
        ]);
```

One caveat, though: the options array must have the same key and value for each item. Otherwise, the value sent to the controller is the numeric key of the item, for existing items.

```
'options' =>[
  'video' => 'video',
  'image' => 'image'
],
```

One obviously needs to provide a model mutator to save the new values and also some method to hydrate all options.

Now all you need to do is update the documentation :)

**Comment by tabacitu** [comment]
Whoaw - this suggestions sure has slipped through the cracks 😔 Trying to wrap up old issues, and like @dandarie said above, we can now do exactly this using the built-in `select2` field. So I'm going to close this issue - I don't think an add-on for this is needed. I would _happily_ publish a tutorial on this though, if anybody wants to write one in our Backpack blog. 1200+ developers would see it, and it's a great way to promote your own blog, brand etc.

Thanks a lot for collaborating here, Chris and everyone else. Apologies for replying so late.
Cheers!

**Comment by dandarie** [comment]
More important is to update the docs. I myself have forgotten about this and needed it some time ago, then came back to this after searching for a solution.

Will this still work in v6?
