### ISSUE TITLE
[Add-on][Has Code] JSON field and column

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/addons#19]
As I [explained here](https://github.com/Laravel-Backpack/CRUD/pull/3239#issuecomment-709240343), I don't think we'll have a built-in JSON field and column, because it would make it too easy for devs to create admin panels _for devs_, not _for normal people_.

But I still think this is a valid use case. Hell, backpackforlaravel.com uses the json_editor field 👀 

So I think it would be AWESOME if we had an add-on that brought advanced functionality - the `json` field and `json` column. And if we want that, we just swap the built-in simple field/column with the advanced one, by specifying the view namespace.

The way I see it:
- one package for both, with the same name (`json` field and `json` column) would be most intuitive;
- a good name for SEO would probably be `json-field-and-column-for-backpack` - a bit lengthy but it will at least show up in searches;

I'd LOVE to have this, and promise to use it ❤️ Best of all, it already has working code for both:
- https://github.com/Laravel-Backpack/CRUD/pull/2406
- https://github.com/Laravel-Backpack/CRUD/pull/3239

Who wants to do this? @ziming ? @stephanus-stuff ? anybody else?

**Comment by tabacitu** [comment]
PS. Of course, if you both want to create a package for your field/column, two packages will do just fine too:
- `ziming/json-field-for-backpack`
- `stephanus-stuff/jsonc-column-for-backpack`

and you could recommend each other's package in the README as complementary.

Let me know. Pretty excited about this! 🥳

**Comment by ziming** [comment]
Hmm will think about it.

**Comment by ziming** [comment]
Ok i created the repo and invited you ( @tabacitu ) and @vesper8

There are no code there yet, I will add when free (which could be quite a while). Either of you can go ahead if you wishes.

**Comment by ziming** [comment]
Hi @tabacitu 

Just published it, I tagged it at 0.1 pre-release

https://github.com/ziming/json-field-for-backpack

Feel free to fix any issues spotted before we make it 1.0

**Comment by tabacitu** [comment]
Excellent @ziming ! What great news 🥳 🎉 I'm proud to say I was download no 1 😆 I've just submitted some PRs with docs and stuff like that. I've tested it and it worked fine for me! Good job!

Let me know when you're ready to make this public, when you tag a stable release, and I'll add it to the Backpack website and promote it to our community.

Cheers!

**Comment by ziming** [comment]
Ok sure, let me know by end of the month if you spot any new issues, if no issues we can tag a 1.0 release

**Comment by ziming** [comment]
Oct has ended. After giving it some thought, I will tag the 1.0 release on 17 Nov. Hope you don't mind the wait.

It's a particular special date for me for personal reasons.

Thank you

**Comment by pxpm** [comment]
I find it quite embracing when people have special times/persons. I hope it's special for the best, if not, that you could make it special for some reason. Waiting for 17 Nov. 👍 
Best,
Pedro

**Comment by tabacitu** [comment]
I think that was the right approach to tag it @ziming 😂, I forgot about it too. 
Still - I have been using the field in production and enjoying it, excellent job on it!

To promote it, I've just finished:
- [x] adding it to our addons page - https://backpackforlaravel.com/addons . It's at the bottom right now, which is a bit inconvenient. But we do plan to rewrite that page to make it sort of a marketplace, and when we do that it'll have a more prominent spot, or be easier to find, I hope.
- [x] creating [an article for it on our blog](https://backpackforlaravel.com/articles/recommendations/new-community-addon-json-field-type) which means it'll also go out to our Article Digest subscribers; that's not a huge amount of people since we just started doing the Digest, but fortunately it's enough to get the ball rolling; we intend to slowly but surely grow the number of Digest subscribers, so future add-ons will benefit from more attention than now;
- [x] posting a link on Laravel-News about it, so that hopefully more Backpack devs who follow that source see it too;

Taken together, an audience in the thousands has definitely been reached, it should provide a great start for the addon.

More things we can do to promote it:
- [x] post on Backpack's Facebook page;
- [x] post from Backpack's Twitter account;
- [ ] post on Reddit, in /r/laravel;
- [ ] post on dev.to or other developer communities;
- [ ] post inside the Laracasts forum;
- [ ] post on laravel.io;

@ziming  are you a member of any of the communities above? In that case it'd be better if it came from you, as a show-and-tell post.

**Comment by ziming** [comment]
Hi @tabacitu 

Thanks for the write up! I enjoyed reading it. As a side note, I do use the field for non technical admins as well. But in read only mode.

If I may have a small request, it will be that I hope you could skip /r/laravel & /r/php, as I'm a little afraid of people who knew me in real life might see it.

While I do have accounts in the other channels you mentioned, I don't really use those accounts. So I don't think I will be making any posts

Other than that, things should be good!

**Comment by tabacitu** [comment]
Sure, no problem @ziming ! I think we've done enough for the moment to hopefully get the ball rolling. Let's see how it goes.
🎉🥳🎈Congrats for the package launch! 😀 👏👏👏

**Comment by promatik** [comment]
@ziming the field looks neat! I'm really looking forward for an opportunity to use it ahah
Well done 👌

**Comment by azaricstefan** [comment]
I have to write it here also: **GREAT WORK**! 🥇 🥇 🥇 🥇 😄 
I needed this field desperately, @ziming thanks for creating this addon.
Be proud of this, it will help many current Backpack users and who knows how many of new users.

Thanks a lot!

**Comment by azaricstefan** [comment]
Maybe it will be useful to others, I can explain shortly my scenario.

In non-admin part of my project users edit google_address field where they type the address and set it for their companies.
Sometimes it happens that google doesn't have up to date address and editing of that particular address (json field) was painful (until now).
This field gives me a way to edit that field in admin panel and set coordinates manually and to override the JSON field itself.
