### ISSUE TITLE
Loading composer repositories with package information     Authentication required (repo.backpackforlaravel.com):

### ISSUE THREAD

**Issue by firecentaur** [Laravel-Backpack/addons#33]
hi there, 

I followed the installation steps for devTools, and it has been working for weeks, except today, when I do composer update, I get an error message:

Loading composer repositories with package information
    Authentication required (repo.backpackforlaravel.com):

**Comment by tabacitu** [comment]
Hi @firecentaur ,

Sorry for the bad experience 🙏

Our servers have been under heavy attack for a few hours yesterday. Unfortunately, the measures we took to combat the attack have reduced our availability in a few geographic areas, close to the attack origin, affecting the repo API. You might have also seen a Captcha when visiting our website. Neither of those is ok, so we’re working on better ways to do this next time.

We’re all good now, the threat is contained and everything should work fine for you again. 
Let us know if that’s not the case.

Thank you for understanding.

**Comment by firecentaur** [comment]
Thanks I'll try again
