### ISSUE TITLE
[Addons] [Request] Changelog

### ISSUE THREAD

**Issue by skpr-repo** [Laravel-Backpack/addons#41]
Hello, since I bought every addon available and I'm tweaking them with vendor:publish (without touching the vendor folder), is it possible to have a changelog for each addon's update?

Some published assets (like the minor_update_client_logic.blade.php for the Editable Columns) are quite huge and I need to be aware of changes in these assets, so I can update them.

I found an old issue about the changelog, but the url provided does not seem to work anymore.

Thanks

**Comment by tabacitu** [comment]
@skpr-repo you discovered a skeleton in our closet 😀 We did have an accurate changelog, but some changes on Github made it out-of-sync. I totally agree with you, having an accurate changelog of our releases, for our premium add-ons, is a MUST. We're working on it, this week @phpfour is trying to figure out a solution. Let's move the conversation to https://github.com/Laravel-Backpack/ideas/issues/156 please 🙏
