### ISSUE TITLE
[Add-on] Dropzone field type

### ISSUE THREAD

**Issue by skys215** [Laravel-Backpack/addons#8]
Hi, 
    I see image field and multiple file upload field. But it seems that there's no multiple image upload field. It should work like the combination of image field and multiple file upload filed, a multiple file upload field with the image preview.
    Hope to see this field type added in the project.
Thanks.

**Comment by tabacitu** [comment]
Update: @eduardoarandah worked on something that not only provides a dropzone field, but an integration with spatie/media-library. Check it out here - https://github.com/eduardoarandah/medialibrary-dropzone-for-laravel-backpack/issues/6 

It's a first draft, but testing & feedback would be greatly appreciated, before it's tagged and released.

---

@ducho indeed that's the problem. For the Create operation you don't already have an `$entry` so you have nothing to tie the uploads to. One quick&dirty solution would be for the field to just include the `upload` field on Create, and then have the dropzone on `Update`. But... it feels a bit hacky.

**Comment by prodixx** [comment]
If you don't want to use spatie's media-library package, and you work (just like me) with a dedicated images column on models, you can try my package - https://github.com/prodixx/dropzone-field-for-backpack

**Comment by eduardoarandah** [comment]
> If you don't want to use spatie's media-library package, and you work (just like me) with a dedicated images column on models, you can try my package - https://github.com/prodixx/dropzone-field-for-backpack

@prodixx it's a pretty cool package!
So, you save images in a json column, right?

**Comment by prodixx** [comment]
@eduardoarandah yes, i forgot to mention that into description.

thank you.

**Comment by ashek1412** [comment]
Hello guys... I am desperately looking for a dropzone solution for backpack 5. can anyone help ???

**Comment by eduardoarandah** [comment]
> Hello guys... I am desperately looking for a dropzone solution for backpack 5. can anyone help ???

@ashek1412 as you can see in my repo, integration with dropzone isn't that hard. 
https://github.com/eduardoarandah/medialibrary-dropzone-for-laravel-backpack

Tricky part is integrating with your media library solution, you know.. creating a thumbnail, sorting, deleting. 
My solution relies on "media library" by spatie and is oriented to pictures. 

I'm sure it can be improved to a more general solution, not only pictures. 

Also, on the frontend I use vue, axios, sortablejs via CDN. This can be improved to a more vanilla solution

**Comment by prodixx** [comment]
@ashek1412 haven't test it yet maybe i'll find some time in weekend to do it

**Comment by tabacitu** [comment]
I have GREAT news on this. We have a Dropzone field in Backpack v6, baked into PRO 🎉 
Backpack v6 is in public beta right now, so you can start using it right away.

Thanks everyone for contributing to this over the years, your code and examples and ideas helped a lot. It hasn't been easy to create the Dropzone field - in fact @jorgetwgroup and @pxpm spent over 3 months on this 🤯 because an _official_ field like this has to support all Backpack features (repeatable, CrudField JS library, different events etc) but... it's here, and it's freaking awesome. Check out the docs here - https://backpackforlaravel.com/docs/6.x/crud-fields#dropzone-pro
